### ISSUE TITLE
ACF fields not showing on graphiql console

### ISSUE THREAD

**Issue by DarioRega** [wp-graphql/wp-graphql-acf#133]
Hello,
First of all, thanks for the amazing work you're doing offering theses plugins :)

I've followed many different videos to set up wp-graphql and add some custom fields including @jasonbahl  tutorial on youtube, and everything result the same.
 
Wordpress Version:  5.4.1

After i've added some custom fields through my posts and checked show in in graphql the group and the fields, when i'll query it i just get the possibility to get the  **"fieldGroupName": "acfDemoFields"**, but nothing else with my fields.

List of plugins i've installed : 
![image](https://user-images.githubusercontent.com/48969740/80991022-acb35200-8e37-11ea-92cf-80128f867203.png)

Graphql schema : 
![image](https://user-images.githubusercontent.com/48969740/80991360-3105d500-8e38-11ea-8f4c-7ffc82afcbe7.png)

Graphql query:
![image](https://user-images.githubusercontent.com/48969740/80991808-e2a50600-8e38-11ea-9ff2-2f89593d29b2.png)

Custom field group : 
![image](https://user-images.githubusercontent.com/48969740/80991252-0287fa00-8e38-11ea-972c-6bc0f1880ec3.png)

I really don't have any idea why it doesn't show up
Im on linux but i've tried aswell on windows, to see if there is any difference, not at all.

Thanks for your time

**Comment by jasonbahl** [comment]
@DarioRega after adding fields to an ACF Field Group, make sure to save the update in ACF and then make sure to refresh the GraphiQL page as well as the Schema needs to be re-fetched and loaded to GraphiQL

The field name will be added to the Schema as `justATextField` I believe.

**Comment by jasonbahl** [comment]
Also, do you happen to have mulitple field groups with "acfDemoFields" as the GraphQL name? That could cause issues if you have one registered in PHP or JSON, and then again in the ACF Fields GUI.

**Comment by saleebm** [comment]
Hey @jasonbahl, I can confirm this issue. I was just looking into it too. Since pulling the latest WP-GraphQL from the dev branch, I noticed this issue. I believe it comes down to the [WP-GraphQL commit 'bug/acf-#130-field-names-should-adhere-to-spec' ](https://github.com/wp-graphql/wp-graphql/commit/b91be33da8e96faa17899f6d62a19db656a8beab).

I tried the commit right before that one, and the fields show up fine. I think it's a formatting issue with the type registry format_key function, something's not matching up.

![1](https://user-images.githubusercontent.com/34875122/80994994-8972ad80-8e0b-11ea-954b-ff5e8892b687.png)

![2](https://user-images.githubusercontent.com/34875122/80994970-824b9f80-8e0b-11ea-9723-89e750df257c.png)

**Comment by jasonbahl** [comment]
Ah! Thanks for the added context. Will dig into this.

**Comment by DarioRega** [comment]
Thanks for your quick response, i've got only one custom group and i'll repeated the updates multiple times to be sure, but it doesn't change.

Good thing @saleebm  got it too, beceause i've didn't see much people having this issue.

Anyway, thank you for looking into this :)

**Comment by jasonbahl** [comment]
@DarioRega ya, looking into this a bit more, I think I might need to revert a recently merged PR in WPGraphQL core. It's going to lead to a lot of breaking changes for the ACF extension 🤔

**Comment by jasonbahl** [comment]
@DarioRega I reverted: https://github.com/wp-graphql/wp-graphql/pull/1293

Will need to look into this a bit further. See if there's some middle ground to promote GraphQL field / type name best practices, but also allow flexibility when not perfectly followed. 

I _am_ working on a major rewrite of WPGraphQL for ACF though, and it will change a _lot_ of Type Names and provide more explicit settings for field names (instead of implicitly mapping the acf field name to GraphQL). 

Keep an eye out for that.

**Comment by jasonbahl** [comment]
@DarioRega @saleebm Thanks again for reporting this. 

Can ya'll try with the latest `wp-graphql` dev branch and let me know if things are working again for you?

**Comment by saleebm** [comment]
@jasonbahl Thank you!

All works fine now. I'm really excited for what's in store for the future with this.

**Comment by DarioRega** [comment]
Sorry for the late response, @jasonbahl i've just tried it out, it display my fields perfectly now, thank you ! Amazing work :)

**Comment by donpernino** [comment]
Hey,

Not sure if I have to create a new issue but I am running the same issue since I have followed @jasonbahl tutorial on youtube and I don't see any of ACF fields I have created on the WP Graphiql interface.

Versions I am using :

WP GraphiQL: `1.0.1`
WP GraphQL: `0.13.3`
WPGraphQL for `Advanced Custom Fields: 0.3.4`

I have tried to save and modify my ACF fields in order to update but this hasn't changed anything.

**Comment by div-cowboy** [comment]
Ran into this issue and was able to resolve it by changing the ACF field group to show on specific pages/posts instead of trying to apply the fields to pages based on the page template. @jasonbahl any chance the plugin could be updated to work with template logic?

**Comment by donnervetter** [comment]
> Ran into this issue and was able to resolve it by changing the ACF field group to show on specific pages/posts instead of trying to apply the fields to pages based on the page template. @jasonbahl any chance the plugin could be updated to work with template logic?

I second this - I was expecting that fetching fields for custom page templates would work out of the box and spent a good 30 minutes googling just to bump here. Really hoping to see this working soon.
