### ISSUE TITLE
ACF Post Object in a Repeater Field - cannot query field

### ISSUE THREAD

**Issue by kodepine** [wp-graphql/wp-graphql-acf#136]
I've got a Post Object, in a repeater field - that fetches data from a custom post type.
No data is returned i graphql

I've tested with a text-field, and thats returns data just fine.

![graf-04](https://user-images.githubusercontent.com/23209689/81204836-1ebba080-8fca-11ea-9652-f4f20cf8d868.png)
![graf-03](https://user-images.githubusercontent.com/23209689/81204838-1f543700-8fca-11ea-8940-c3334e849884.png)
![graf-02](https://user-images.githubusercontent.com/23209689/81204842-1feccd80-8fca-11ea-8b2b-32f1923c3a9b.png)
![graf-01](https://user-images.githubusercontent.com/23209689/81204845-20856400-8fca-11ea-8b05-868f91a1d5a5.png)

**Comment by jasonbahl** [comment]
@kodepine do you have the `engine` post type set to `Show in GraphQL`?

**Comment by kodepine** [comment]
> @kodepine do you have the `engine` post type set to `Show in GraphQL`?

Like this?

![graf-05](https://user-images.githubusercontent.com/23209689/81219362-00f93600-8fe0-11ea-93c0-0ede8b5e2aa4.png)

**Comment by jasonbahl** [comment]
Ya. Hmm. This looks all correct on quick glance. I'll need to dig in. 

**One note**: On the Post Type registry, you shouldn't need `graphql_singular_name` and `graphql_plural_type`, just `graphql_single_name` and `graphql_plural_name`

**Comment by kodepine** [comment]
Thank you. Let me know if you want me to test anything.

I've changed the register_post_type accordingly

**Comment by jasonbahl** [comment]
@kodepine I'm not sure my answer this late will be helpful, but I'll add some insight anyway. 

I believe the issue here is that the `Post Object` field returns a Union (and will be changing to an Interface in v0.6.0 (#262). 

To reproduce, I did the following: 

## Registered the Post Type: 

```php
add_action( 'init', function() {

	register_post_type( 'engineCpt', [
		'show_ui' => true,
		'label' => 'Engine',
		'show_in_graphql' => true,
		'graphql_single_name' => 'EngineCpt',
		'graphql_plural_name' => 'EngineCpts'
	] );

});
```

## Published a Post in the Post Type:

![Screen Shot 2021-05-14 at 3 17 52 PM](https://user-images.githubusercontent.com/1260765/118332659-abdfe200-b4c7-11eb-987c-de8340d34bfe.png)

## Created the Field

I created a Post Object field in my field group and named it `sEngine`. 

![Screen Shot 2021-05-14 at 3 19 31 PM](https://user-images.githubusercontent.com/1260765/118332736-c9ad4700-b4c7-11eb-813a-a59722a37963.png)

## Update Post with Engine Selected

![Screen Shot 2021-05-14 at 3 20 16 PM](https://user-images.githubusercontent.com/1260765/118332789-e5185200-b4c7-11eb-8be7-8238c9b3515e.png)

## Query the field in GraphQL

### v0.5.2

In WPGraphQL for ACF v0.5.2 and older, the Post Object field type returns a Union in the GraphQL Schema, which means that you must specify what fields you want based on the Type that's returned. 

Because the Post could be of any Post Type, it's not possible to know until runtime which Type will be returned, so you specify in the query like so:

```graphql
...
{
  post(id: 2179, idType: DATABASE_ID) {
    id
    databaseId
    postTest {
      sengine {
        __typename
        ... on EngineCpt {
          id
          title
        }
      }
    }
  }
}
```

And would get results like so:

![Screen Shot 2021-05-14 at 3 25 28 PM](https://user-images.githubusercontent.com/1260765/118333260-a1721800-b4c8-11eb-9155-e2c95ab2daf3.png)

### v0.6.0
In v0.6.0 (#262) this will be changing a bit. The `Post Object` field type will return a [Connection](https://www.wpgraphql.com/docs/connections/) to the `ContentNode` interface, instead of a PostObjectUnion, so you could query like so: 

```graphql
{
  post(id: 2179, idType: DATABASE_ID) {
    id
    databaseId
    postTest {
      sEngine {
        node {
          __typename
          id
          ... on EngineCpt {
            id
            title
          }
        }
      }
    }
  }
}
```

![Screen Shot 2021-05-14 at 3 23 02 PM](https://user-images.githubusercontent.com/1260765/118333060-4809e900-b4c8-11eb-916c-cc20465a9b18.png)
