### ISSUE TITLE
Query taxonomy term inside ACF Repeater field

### ISSUE THREAD

**Issue by elvismdev** [wp-graphql/wp-graphql-acf#16]
Hi,

I have an ACF Repeater field, with different types of fields inside of it. One of them is a WordPress Taxonomy, for which I cannot find how to return the values of the terms on it, it keeps returning just empty `[]` values.

Here some screenshots to illustrate my ACF fields setup.

![Screen Shot 2019-07-09 at 5 16 41 PM](https://user-images.githubusercontent.com/3847077/60931378-463cc200-a26e-11e9-9a5b-99f97d28b184.png)

![Screen Shot 2019-07-09 at 5 17 00 PM](https://user-images.githubusercontent.com/3847077/60931397-55bc0b00-a26e-11e9-8ff8-14a32e140834.png)

Here my query and the results from GraphQL, where it returns empty values for the taxonomy `Indicator`, despite that in my query I'm requesting their taxonomy ID and name.

![Screen Shot 2019-07-09 at 5 19 47 PM](https://user-images.githubusercontent.com/3847077/60931525-974cb600-a26e-11e9-8298-c423d015ada7.png)

![Screen Shot 2019-07-09 at 5 19 52 PM](https://user-images.githubusercontent.com/3847077/60931532-9f0c5a80-a26e-11e9-8913-279408934b60.png)

What I'm missing here?

**Comment by jasonbahl** [comment]
Thanks for reporting with such detail. I’ll look into this tomorrow and follow up.

**Comment by elvismdev** [comment]
If this helps for more context, I moved the taxonomy out of the Repeater field, like to make it be just a standalone Taxonomy type field in ACF, and got the same results. 

![Screen Shot 2019-07-09 at 9 14 04 PM](https://user-images.githubusercontent.com/3847077/60940202-82cce580-a28f-11e9-9679-3a5a1800a1fe.png)

![Screen Shot 2019-07-09 at 9 14 14 PM](https://user-images.githubusercontent.com/3847077/60940217-8bbdb700-a28f-11e9-8071-a3821d1fa27f.png)


After this last attempt that makes me think (in case this is a bug) that this is not related with having the Taxonomy type field nested inside a Repeater ACF field. It looks like `wp-graphql/wp-graphql-acf` currently is not capable to query the Taxonomy terms from ACF.

Because for the record, querying this Taxonomy the regular way it does returns the terms values as expected. 

![Screen Shot 2019-07-09 at 9 33 13 PM](https://user-images.githubusercontent.com/3847077/60940768-7fd2f480-a291-11e9-984b-eef314ac7936.png)

![Screen Shot 2019-07-09 at 9 33 23 PM](https://user-images.githubusercontent.com/3847077/60940777-86fa0280-a291-11e9-9b21-a149634902a4.png)

**Comment by jasonbahl** [comment]
@elvismdev I'm looking into this now.

**Comment by elvismdev** [comment]
Thanks @jasonbahl !

**Comment by henrikwirth** [comment]
@jasonbahl I have the same Issue with Taxomony-Fields inside a Flexible Content layout

**Comment by henrikwirth** [comment]
Okay so the problem I had with taxonomies was actually a different one. I didn't get all the pages with all the childPages and therefore the childPage with the taxonomy field wasn't available.

**Comment by moonmeister** [comment]
I'm having an issue where in Flexible Content fields I only get a type and can't access any data. Is this the same issue? Or do I have a separate issue?

**Comment by jasonbahl** [comment]
I believe this issue comes from how WPGraphQL Core loaded terms in hierarchical taxonomies. 

For a while, WPGraphQL Core's loader would load _only_ top level terms with parent=>0, and you had to explicitly ask for children. 

In the case of this ACF field, the underlying query ended up being something like: 

```php
$query = new WP_Term_Query( [
  'include' => [ 1, 2, 3 ]
  'parent' => 0
] );
```

And let's say terms `2` and `3` were child/grandchild. 

This query would return _just_ term 1, because it's the only one with `parent => 0`.

This was fixed in WPGraphQL core and from my testing this seems to be working in WPGraphQL for ACF now. 

## Current

Current behavior with:

- WPGraphQL v1.3.8
- WPGraphQL for ACF v0.5.2
- ACF Pro v5.9.4

I can set the value of a taxonomy field in a repeater with a top-level term and a grandchild term and get these terms in the response: 

![Screen Shot 2021-05-13 at 1 08 24 PM](https://user-images.githubusercontent.com/1260765/118174633-4d920100-b3ec-11eb-8614-5293bb0bc1fc.png)


## Upcoming v0.6.0

In the upcoming v0.6.0 release, the shape of the query changes a bit to respect the `post->terms` [connection](https://www.wpgraphql.com/docs/connections/) better, but the functionality of returning related terms whether they are top-level or children, remains.

![Screen Shot 2021-05-13 at 1 01 27 PM](https://user-images.githubusercontent.com/1260765/118173856-5504da80-b3eb-11eb-8b50-af6ed9883302.png)
