### ISSUE TITLE
wp-graphql - acf repeater field child image data displayed outside of ROOT_QUERY object

### ISSUE THREAD

**Issue by DanielBarbakadze** [wp-graphql/wp-graphql-acf#185]
WPGraphiQL IDE displays correct data like this:

![WPGraphiQLIDE](https://i.stack.imgur.com/3K6Kv.png)

but when I make the same query with Apollo Client on the Front-End(NextJS) acf repeater field child image data displayed outside of ROOT_QUERY object as MediaItem:{id} like this:

![consoleLog](https://i.stack.imgur.com/4468e.png)

This only happens when I use image field as a repeater subfield:

![wp](https://i.stack.imgur.com/OtvTz.png)

**Getting data with query in NextJS:**

```
![stack1](https://user-images.githubusercontent.com/49524283/98332393-06c7e680-2018-11eb-9848-7f7d56a7a152.png)

import React from "react";
import { initializeApollo } from "../lib/apolloClient";
import { gql } from "@apollo/client";

const Home = (props) => {
  return <>{console.log("home", props)}</>;
};

export async function getStaticProps() {
  const apolloClient = initializeApollo();

  await apolloClient.query({
    query: gql`
      {
        page(id: "Home", idType: URI) {
          acfHomePage {
            acfTest {
              testImages {
                test {
                  id
                }
              }
            }
          }
        }
      }
    `,
  });

  return {
    props: {
      initialApolloState: apolloClient.cache.extract(),
    },
  };
}

export default Home;
```

**Comment by jasonbahl** [comment]
👋  ApolloGraphQL caches nodes in a normalized way. 

Since items in the Graph can be accessed from many different entry points in the Graph, Apollo takes the nodes and caches them based on their type and ID. 

This means that if a Query were to ask for the same object multiple times, instead of having multiple records of that object in the client cache, Apollo would have 1 record it could reference.

This is expected behavior for Apollo Client. You can read a bit more about this here: https://www.apollographql.com/docs/react/caching/cache-configuration/#data-normalization
