### ISSUE TITLE
ACF Number Fields with "0" value return null

### ISSUE THREAD

**Issue by tomwhita** [wp-graphql/wp-graphql-acf#237]
System Info:
- ACF Pro v5.9.3
- WPGraphQL v1.2.5
- WP Gatsby v0.9.2
- WPGraphQL for Advanced Custom Fields v0.4.0

### To reproduce:
- Using ACF Pro create a field group for posts and add a number field to the group
- Set the field value on a post to `0`
- Using Graphiql, query for the post and custom field.  The value should return as `null`

**Comment by jasonbahl** [comment]
This is fixed in the upcoming WPGraphQL v0.6.0 (#262)

# Before

Querying a number field with a value of `0` returns `null`.

![Screen Shot 2021-05-13 at 12 48 53 PM](https://user-images.githubusercontent.com/1260765/118172421-94cac280-b3e9-11eb-9f94-0c0fd1a2a960.png)

## After

Querying a number field with a value of `0` properly returns `0`

![Screen Shot 2021-05-13 at 12 47 54 PM](https://user-images.githubusercontent.com/1260765/118172312-7238a980-b3e9-11eb-957a-f95cfd232050.png)
