### ISSUE TITLE
Only __typename is available in an ACF post object

### ISSUE THREAD

**Issue by jackharding** [wp-graphql/wp-graphql-acf#240]
Apologies if I've missed some documentation explaining this but I can't seem to retrieve anything from a post object besides __typename. In the example below I've made two test fields, one for a post object that's set to return an object and another to just return the ID of the post.
![Screenshot 2021-03-27 at 10 06 33](https://user-images.githubusercontent.com/12549439/112717398-51bd9a00-8ee4-11eb-9a88-67bcee94596f.png)

**Comment by RodrigoTomeES** [comment]
Hello, does this happen to you? #239

**Comment by jasonbahl** [comment]
@jackharding The Post Object field currently returns a `Union`

So you need to query like so: 

```
...on Page {
  id
  title
}
...on Post {
  id
  title
}
```

You can see an example in the README here: https://github.com/wp-graphql/wp-graphql-acf#post-object-field

----

The plan is to change this field to be a proper one-to-one connection that will return a ContentNode Interface instead of a Union. Keep an eye out for that change.
