### ISSUE TITLE
Serving formatted text using GraphQL?

### ISSUE THREAD

**Issue by gabrielishere** [wp-graphql/wp-graphql-acf#328]
Hi

I am currently using ACF to create some custom field types, I am using a combination of React and GraphQL to fetch the data I need. One of the field types I want to include is **Text Area**

I have noticed there are three options for formatting:

![image](https://user-images.githubusercontent.com/70941048/182594041-81ed3123-1e97-4720-877f-0d1167a2dbd6.png)

I tried all of these options, but my paragraphs do not seem to be rendering. How do I implement this correctly? Does the plugin have capacity to go beyond paragraphs and include additional links as well? 

My implementation is using Apollo client, and then GraphQL. 

import { ApolloClient, InMemoryCache } from "@apollo/client";
```

const client = new ApolloClient({
  uri: "https://mysiteonline/graphql",
  cache: new InMemoryCache(),
});

export default client;


const GET_ALL_MEDIA = gql`
  {
    myMedias(first: 300) {
      edges {
        node {
          myACFMeta {
            title
            image {
              mediaItemUrl
            }
            projectDescription
          }
        }
      }
    }
  }
`;
```

And then this is my component:

```

  const { loading, error, data } = useQuery(GET_ALL_MEDIA);

  if (loading) {
    return (
      <div className="display-main">
        <img className="loading-img" src={loadingImage}></img>
      </div>
    );
  }

  if (error) {
    return <div className="display-main">":("</div>;
  }

  const {
    myMedias: { edges },
  } = data;


  return (
    <div>
     <p>{myMedias[0].projectDescription}</p>
    </div>
  );
}
```

The current text format displays unformatted. What steps am I missing?

**Comment by jasonbahl** [comment]
👋🏻 I believe this issue was resolved back in 2019? see: https://github.com/wp-graphql/wp-graphql-acf/pull/95/files

We're re-building this plugin over here: https://github.com/wp-graphql/wpgraphql-acf (and we'll be archiving this repo in the not-too-distant future) and I've tested this functionality on the new version as well and things seem to be working. 

### No Formatting

![CleanShot 2023-10-30 at 14 22 41](https://github.com/wp-graphql/wp-graphql-acf/assets/1260765/ca126480-3e98-4057-b7d0-a92588825827)


### Automatically Add Paragraphs

![CleanShot 2023-10-30 at 14 23 02](https://github.com/wp-graphql/wp-graphql-acf/assets/1260765/43dab2d0-adeb-415b-bb45-fb32f2a22db0)

----

If you're able to test the new version of the plugin and find that it's not acting as you'd expect, please open a new issue on that repo with clear steps to reproduce. Thanks! 🙏🏻
