### ISSUE TITLE
add where: filter to ACF added field values

### ISSUE THREAD

**Issue by dialformonkey** [wp-graphql/wp-graphql-acf#331]
As i am not familiar with wordpress finding it hard to apply a filter where: to the ACF fields exposes via the graphql api. 

Current using wpgraphql woocommerce plugin as well. 

if anyone could help point out how i'de go about this would be greatful.

<img width="1736" alt="Screen Shot 2022-09-09 at 10 18 17 PM" src="https://user-images.githubusercontent.com/62189575/189408331-0b072a20-3997-446b-b2c1-6094f8c5c575.png">

**Comment by prosperofilipe** [comment]
@dialformonkey do you need something like this -> [https://wpgraphql.com/2020/04/14/query-posts-based-on-advanced-custom-field-values-by-registering-a-custom-where-argument/](https://wpgraphql.com/2020/04/14/query-posts-based-on-advanced-custom-field-values-by-registering-a-custom-where-argument/) ?

**Comment by jasonbahl** [comment]
closing this issue as we don't plan to support filtering out of the box (at least not now) due to how much of a negative impact Meta Queries can have on a WordPress server. 

If you need this functionality, and feel like it's safe for your API to support, the documentation linked above should point you in the right direction. 

Also, note that we're re-building WPGraphQL for ACF over here: https://github.com/wp-graphql/wpgraphql-acf and will be archiving this repo in the not-too-distant future
