### ISSUE TITLE
PHP Deprecated:  Optional parameter $and_params declared before required parameter $param

### ISSUE THREAD

**Issue by DevelopMod** [wp-graphql/wp-graphql-acf#369]
Hello, 
So I'm using lates Wordpress with php 8.1 and latest Graphql, ACF etc... 

Getting this error in my error log:

`[14-Nov-2023 19:27:19 UTC] PHP Deprecated:  Optional parameter $and_params declared before required parameter $param is implicitly treated as a required parameter in public_html/wp-content/plugins/wp-graphql-acf/src/location-rules.php on line 209`

Hopefully that helps, most likely related to php version .

**Comment by jasonbahl** [comment]
@DevelopMod what version of WPGraphQL for ACF are you using? I believe this was fixed in the v0.6.0 release: https://github.com/wp-graphql/wp-graphql-acf/releases/tag/v0.6.0

----

I would highly recommend upgrading to the new version of WPGraphQL for ACF that we're building over here: https://github.com/wp-graphql/wpgraphql-acf. It will be released on WordPress.org in the not-too-distant future and this repo will be archived.

**Comment by DevelopMod** [comment]
I'm actually using the latest version from Wordpress.org, it is Version 0.5.3, I didn't get any update notifications so if that is the case I will just update it to the latest version from the new repo.

Thanks
