### ISSUE TITLE
Getting GraphQL-Error if PostObject is null

### ISSUE THREAD

**Issue by PSMJonas** [wp-graphql/wp-graphql-acf#370]
If I use the "Post Object" field and select a post that has the status Draft, the field returns zero. However, GraphQL throws me an error here:

![Bildschirmfoto 2023-11-15 um 10 32 50](https://github.com/wp-graphql/wp-graphql-acf/assets/64772720/238921cc-ff4c-4a51-b615-50b3cab61075)

**Comment by jasonbahl** [comment]
@PSMJonas this issue has been resolved in the new version of WPGraphQL for ACF that we're working on over here: https://github.com/wp-graphql/wpgraphql-acf.

I'd encourage you to upgrade to that version at your earliest convenience as that's the version we'll be supporting long-term and releasing on the WordPress.org plugin repo. 

I'm going to close this issue as it won't be fixed in this repo (we'll be archiving this repo soon)
