### ISSUE TITLE
Both WPGraphQL (v0.4.0+) and Advanced Custom Fields (v5.7+) must be active for "wp-graphql-acf" to work

### ISSUE THREAD

**Issue by mickaelRamaroson50** [wp-graphql/wp-graphql-acf#371]
Hi,

I have installed a wpgrapql v1.19 but I have still this error

Both WPGraphQL (v0.4.0+) and Advanced Custom Fields (v5.7+) must be active for "wp-graphql-acf" to work

**Comment by jasonbahl** [comment]
@mickaelRamaroson50 hello, you might have installed the plugin by cloning the repo instead of installing it from the .zip on the [releases](https://github.com/wp-graphql/wp-graphql-acf/releases/tag/v0.6.1) page as indicated in the [install instructions](https://github.com/wp-graphql/wp-graphql-acf#install-and-activate-).

That said, I highly recommend you check out the new version of WPGraphQL for ACF being developed over here: https://github.com/wp-graphql/wpgraphql-acf. 

It's a complete re-architecture and solves a lot of issues. This repo will be archived in the not-too-distant future.
