### ISSUE TITLE
Post Object field showing an error

### ISSUE THREAD

**Issue by metawise** [wp-graphql/wp-graphql-acf#46]
Please tell what am I doing wrong?

![Screen Shot 2019-08-16 at 2 31 33 PM](https://user-images.githubusercontent.com/14798623/63199392-99a2ec80-c032-11e9-827f-57a4458ad0ed.jpg)

**Comment by jasonbahl** [comment]
@metawise I believe this is no longer an issue. 

The issue was caused by orphaned IDs being set as the value of the relationship. 

So, in your case you have id `1` as the relationship value, and my guess is that post with id `1` has since been deleted. 

To reproduce this, I've done the following: 

## Created a `relatedPosts` field of the "relationship" field type

![Screen Shot 2021-05-14 at 9 59 46 AM](https://user-images.githubusercontent.com/1260765/118297247-20505c00-b49b-11eb-8102-faf661786deb.png)

## Published a post 

I published a post titled "Post to Trash" so that we can use it in the relationship field

![Screen Shot 2021-05-14 at 10 02 44 AM](https://user-images.githubusercontent.com/1260765/118297536-8937d400-b49b-11eb-90cc-b9dab16a8270.png)


## Edited a post, adding a the "Post to Trash" as a related post

![Screen Shot 2021-05-14 at 10 03 14 AM](https://user-images.githubusercontent.com/1260765/118297587-9a80e080-b49b-11eb-9103-35c1ea3785a1.png)

## Delete the "Post to Trash" post

Next, I deleted the "Post to Trash" post, but left the ID of it stored as a relationship. 

## Query the Relationship

### v0.5.2

In v0.5.2 of WPGraphQL for ACF, I can query this like so: 

```graphql
{
  post(id: 2179, idType: DATABASE_ID) {
    id
    postTest {
      relatedPosts {
        ...on Post {
          id
          databaseId
        }
      }
    }
  }
}
```

![Screen Shot 2021-05-14 at 10 46 11 AM](https://user-images.githubusercontent.com/1260765/118302563-9b1c7580-b4a1-11eb-9d8c-7ba7f87caef6.png)

And we can see that I get a `null` result, but no errors. The ID of the trashed post is still stored as the value, but WPGraphQL knows that it's not a valid object, and doesn't load it. 

### v0.6.0 (#262)

**Note:** _v0.6.0 makes some changes to the shape of the Schema for relationship fields, so I wanted to point this out here._

In v0.6.0 of WPGraphQL for ACF, I can query this like so: 

```graphql
{
  post(id: 2179, idType: DATABASE_ID) {
    id
    postTest {
      relatedPosts {
        nodes {
          id
          databaseId
        }
      }
    }
  }
}
```

And we can see that I get a `null` result, but no errors. The ID of the trashed post is still stored as the value, but WPGraphQL knows that it's not a valid object, and doesn't load it.
