### ISSUE TITLE
Feature Request: Allow queries to ACF fields specific to a Category

### ISSUE THREAD

**Issue by lyonsv** [wp-graphql/wp-graphql-acf#52]
**Feature**

Category specific ACF fields are not currently available to query and need to be mapped.

**Example**

The below will not appear in our schema: 

![image](https://user-images.githubusercontent.com/2531232/63620959-aacb9a80-c5ea-11e9-9322-7af481b6a1e9.png)

**Comment by RAYAPINAntoine** [comment]
Hi lyonsv, 

I get the same probleme do you find a way to fix it ?

Or if somebody else have already fix this can help us please ?

**Comment by kuworking** [comment]
Me too, is there any link that describes what is enabled currently in this conditional showing?

**Comment by muradbu** [comment]
Is this still being maintained?

**Comment by jasonbahl** [comment]
👋🏻  Sorry for the delay on this! 

With v0.5.0 (#250) this is resolved!

Below is a screenshot showing the location rule adding the field group to a specific post category. 

In the WP Admin, this means the field group will only show for editors to interact with for posts with that category assigned, and in WPGraphQL the field group will be associated with the `Post` type so that the field group can be queried on any `Post` (as the associated categories aren't known until the query is resolved).

![Screen Shot 2021-04-20 at 3 57 44 PM](https://user-images.githubusercontent.com/1260765/115469026-27b07c80-a1f1-11eb-8fed-2a53608cda7e.png)
